version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: 1
  parameter-store:
    DOCKER_HUB_ID: "$SSM_PARAM_NAME_DOCKER_HUB_ID"
    DOCKER_HUB_PW: "$SSM_PARAM_NAME_DOCKER_HUB_PW"

phases:
  build:
    commands:
      - echo "DOCKER_HUB_ID:$DOCKER_HUB_ID"
      - docker login --username $DOCKER_HUB_ID --password $DOCKER_HUB_PW
      -
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "ACCOUNT_ID:$ACCOUNT_ID, REGION:$AWS_REGION"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      -
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "COMMIT_HASH:$COMMIT_HASH"
      - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from=$REPOSITORY_URI:latest --cache-to=$REPOSITORY_URI:cache --target prod --tag $REPOSITORY_URI:$COMMIT_HASH .
      -
      - echo "push to $REPOSITORY_URI:$COMMIT_HASH"
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - docker push $REPOSITORY_URI:cache