name: Feature Test
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  feature-test:
    name: Feature Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0.24
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./app
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./app/go.mod
          cache: true
          cache-dependency-path: ./app/go.sum
      - name: Download dependencies
        working-directory: ./app
        run: go mod download
      - name: Copy .env
        working-directory: ./app
        run: cp .env.feature.example .env.feature
      - name: Install tools
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0
        working-directory: ./app
      - name: Migrate DB
        working-directory: ./app
        run: go run commands/migrate/main.go
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
      - name: Clear test cache
        working-directory: ./app
        run: go clean -testcache
      - name: Test
        run: make test
        working-directory: ./app
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
          MYSQL_DATABASE: test
